defmodule ImmoWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :immo

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  #
  # §10.1 path 5: the staff session cookie is HttpOnly + Secure (in
  # production behind TLS) and SameSite=Lax. `secure: true` is driven by
  # the `:immo, :cookie_secure` compile-time config so it can be
  # overridden per environment (prod = true, dev/test = false).
  @session_options [
    store: :cookie,
    key: "_immo_key",
    signing_salt: "J5SXyp0p",
    same_site: "Lax",
    http_only: true,
    secure: Application.compile_env(:immo, :cookie_secure, false)
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g. in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :immo,
    gzip: not code_reloading?,
    only: ImmoWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :immo
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug ImmoWeb.Router
end
